alias g=git
alias vi=vim
#alias m=mvim
alias nv=nvim

# for mac
alias ls='ls -G'
# for arch
#alias ls='ls --color'

# jupyter notebook
alias nb='jupyter notebook'

# python virtualenv
#alias cmsenv='source ~/.env/cms/bin/activate'

# logins

# ss
#alias ss='/usr/local/opt/shadowsocks-libev/bin/ss-local -c /usr/local/etc/shadowsocks-libev.json'
