alias g=git
alias vi=vim
alias m=mvim

# for mac
alias ls='ls -G'
# for arch
#alias ls='ls --color'

# jupyter notebook
alias nb='jupyter notebook'

# python virtualenv
alias cmsenv='source ~/.env/cms/bin/activate'

# logins
#source ~/.bash_aliases_local
#alias cms1='ssh 10.174.89.71'
#alias api1='ssh 10.80.236.161'
#alias api2='ssh 10.30.49.170'

