execute pathogen#infect()

let g:vimclojure#HighlightBuiltins = 1
let g:vimclojure#ParenRainbow = 1

set viminfo+=!

set modelines=1

"source $VIMRUNTIME/vimrc_example.vim
"set nobackup
"set shiftwidth=4
"set softtabstop=4
"set tabstop=4
""set expandtab
"set autoindent
"set smarttab
"set formatoptions=croql
"
